<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Mileage: Persistence library.</Description>
    <Configurations>Debug;Release;Test</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Jeebs.Auth.Data" />
    <PackageReference Include="Jeebs.Data" />
    <PackageReference Include="Jeebs.Data.Common" />
    <PackageReference Include="Simple.Migrations" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Persistence.Common\Persistence.Common.csproj" />
  </ItemGroup>
</Project>
